### ISSUE TITLE
I am getting a bunch of errors. My arduino IDE is 1.8.5 and stm32 core is 1.7.0

### ISSUE THREAD

**Issue by shuzonudas** [cbm80amiga/Arduino_ST7735_STM#1]
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'void Arduino_ST7735::init()':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:115:67: error: 'DATA_SIZE_8BIT' was not declared in this scope
   SPI.beginTransaction(SPISettings(SPI_FREQ, MSBFIRST, SPI_MODE3, DATA_SIZE_8BIT));
                                                                   ^~~~~~~~~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:115:67: note: suggested alternative: 'SPI_DATASIZE_8BIT'
   SPI.beginTransaction(SPISettings(SPI_FREQ, MSBFIRST, SPI_MODE3, DATA_SIZE_8BIT));
                                                                   ^~~~~~~~~~~~~~
                                                                   SPI_DATASIZE_8BIT
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:136:7: error: 'class SPIClass' has no member named 'setDataSize'; did you mean 'setDataMode'?
   SPI.setDataSize(DATA_SIZE_16BIT);
       ^~~~~~~~~~~
       setDataMode
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:136:19: error: 'DATA_SIZE_16BIT' was not declared in this scope
   SPI.setDataSize(DATA_SIZE_16BIT);
                   ^~~~~~~~~~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:136:19: note: suggested alternative: 'SPI_DATASIZE_16BIT'
   SPI.setDataSize(DATA_SIZE_16BIT);
                   ^~~~~~~~~~~~~~~
                   SPI_DATASIZE_16BIT
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'void Arduino_ST7735::writeCmd(uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:144:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(c);
       ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'void Arduino_ST7735::writeData(uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:153:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(c);
       ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'virtual void Arduino_ST7735::setRotation(uint8_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:183:7: error: 'class SPIClass' has no member named 'setDataSize'; did you mean 'setDataMode'?
   SPI.setDataSize(DATA_SIZE_8BIT);
       ^~~~~~~~~~~
       setDataMode
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:183:19: error: 'DATA_SIZE_8BIT' was not declared in this scope
   SPI.setDataSize(DATA_SIZE_8BIT);
                   ^~~~~~~~~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:183:19: note: suggested alternative: 'SPI_DATASIZE_8BIT'
   SPI.setDataSize(DATA_SIZE_8BIT);
                   ^~~~~~~~~~~~~~
                   SPI_DATASIZE_8BIT
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:216:7: error: 'class SPIClass' has no member named 'setDataSize'; did you mean 'setDataMode'?
   SPI.setDataSize(DATA_SIZE_16BIT);
       ^~~~~~~~~~~
       setDataMode
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:216:19: error: 'DATA_SIZE_16BIT' was not declared in this scope
   SPI.setDataSize(DATA_SIZE_16BIT);
                   ^~~~~~~~~~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:216:19: note: suggested alternative: 'SPI_DATASIZE_16BIT'
   SPI.setDataSize(DATA_SIZE_16BIT);
                   ^~~~~~~~~~~~~~~
                   SPI_DATASIZE_16BIT
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'void Arduino_ST7735::setAddrWindow(uint16_t, uint16_t, uint16_t, uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:227:19: error: 'class SPIClass' has no member named 'write'
   DC_COMMAND; SPI.write(ST7735_CASET);
                   ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:228:16: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(x0); SPI.write(x1);
                ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:228:31: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(x0); SPI.write(x1);
                               ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:230:19: error: 'class SPIClass' has no member named 'write'
   DC_COMMAND; SPI.write(ST7735_RASET);
                   ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:231:16: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(y0); SPI.write(y1);
                ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:231:31: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(y0); SPI.write(y1);
                               ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:233:19: error: 'class SPIClass' has no member named 'write'
   DC_COMMAND; SPI.write(ST7735_RAMWR);
                   ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'void Arduino_ST7735::pushColor(uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:244:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(color);
       ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'virtual void Arduino_ST7735::drawPixel(int16_t, int16_t, uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:253:19: error: 'class SPIClass' has no member named 'write'
   DC_COMMAND; SPI.write(ST7735_CASET);
                   ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:254:16: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(x); SPI.write(x+1);
                ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:254:30: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(x); SPI.write(x+1);
                              ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:255:19: error: 'class SPIClass' has no member named 'write'
   DC_COMMAND; SPI.write(ST7735_RASET);
                   ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:256:16: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(y); SPI.write(y+1);
                ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:256:30: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(y); SPI.write(y+1);
                              ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:257:19: error: 'class SPIClass' has no member named 'write'
   DC_COMMAND; SPI.write(ST7735_RAMWR);
                   ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:258:16: error: 'class SPIClass' has no member named 'write'
   DC_DATA; SPI.write(color);
                ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'virtual void Arduino_ST7735::drawFastVLine(int16_t, int16_t, int16_t, uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:275:9: error: 'class SPIClass' has no member named 'dmaSend'
     SPI.dmaSend(dmaBuf, h, 0);
         ^~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:278:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(color, h);
       ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'virtual void Arduino_ST7735::drawFastHLine(int16_t, int16_t, int16_t, uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:296:9: error: 'class SPIClass' has no member named 'dmaSend'
     SPI.dmaSend(dmaBuf, w, 0);
         ^~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:299:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(color, w);
       ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'virtual void Arduino_ST7735::fillRect(int16_t, int16_t, int16_t, int16_t, uint16_t)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:327:11: error: 'class SPIClass' has no member named 'dmaSend'
       SPI.dmaSend(dmaBuf, DMA_MAX, 0);
           ^~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:329:9: error: 'class SPIClass' has no member named 'dmaSend'
     SPI.dmaSend(dmaBuf, num, 0);
         ^~~~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:332:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(color, num);
       ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'void Arduino_ST7735::drawImage(int16_t, int16_t, int16_t, int16_t, uint16_t*)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:346:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(img16, num);
       ^~~~~
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp: In member function 'void Arduino_ST7735::drawImageF(int16_t, int16_t, int16_t, int16_t, const uint16_t*)':
D:\Software BackUp\arduino-1.8.5-windows\arduino-1.8.5\portable\sketchbook\libraries\Arduino_ST7735_STM-master\Arduino_ST7735_STM.cpp:359:7: error: 'class SPIClass' has no member named 'write'
   SPI.write(img16, num);

**Comment by cbm80amiga** [comment]
I still use stm32duino and Arduino IDE 1.6.5. I will have to look at STM32 core project too.

**Comment by shuzonudas** [comment]
Can you please include the SPI library you are using. I think that is causing the errors.

**Comment by cbm80amiga** [comment]
SPI is part of the core, I doubt it will work that way. You can just install stm32duino additionally (I hope). 
AFAIR my Arduino_STM32 is just copied to Arduino/hardware.

**Comment by shuzonudas** [comment]
Thanks man! I got it working.

**Comment by chendrix4** [comment]
@shuzonudas Did you switch to stm32duino, or get it working with STM32 Core?

**Comment by shuzonudas** [comment]
When I was testing the library I used this arduino core for STM32.
https://github.com/rogerclarkmelbourne/Arduino_STM32
