### ISSUE TITLE
Fails to compile within IDE (using both arduino OR rogers STM32 package)

### ISSUE THREAD

**Issue by sbtoonz** [cbm80amiga/Arduino_ST7735_STM#4]
Please advise on how to use your library?

When installing into the IDE currently and using Rogers STM32 package as mentioned in previous issue example sketches fail to compile

When installing with arduino STM board support the library fails to compile in line missing lots of SPI definitions

**Comment by sbtoonz** [comment]
Arduino: 1.8.13 (Windows 10), Board: "Generic STM32F1 series, BluePill F103C8, STM32CubeProgrammer (Serial), Enabled (generic 'Serial'), CDC (generic 'Serial' supersede U(S)ART), Low/Full Speed, Fastest (-O3), Newlib Nano (default)"





















C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.cpp: In member function 'void Arduino_ST7735::writeSPI(uint8_t)':

C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.cpp:113:5: error: 'SPDR' was not declared in this scope

  113 |     SPDR = c;

      |     ^~~~

In file included from C:\Users\mugen\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.9.0\cores\arduino/Arduino.h:56,

                 from C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.h:28,

                 from C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.cpp:4:

C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.cpp: In member function 'void Arduino_ST7735::init()':

C:\Users\mugen\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.9.0\cores\arduino/pins_arduino.h:297:38: error: cannot convert 'volatile uint32_t*' {aka 'volatile long unsigned int*'} to 'volatile uint8_t*' {aka 'volatile unsigned char*'} in assignment

  297 | #define portOutputRegister(P)       (&(P->ODR))

      |                                     ~^~~~~~~~~~

      |                                      |

      |                                      volatile uint32_t* {aka volatile long unsigned int*}

C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.cpp:143:12: note: in expansion of macro 'portOutputRegister'

  143 |   dcPort = portOutputRegister(digitalPinToPort(dcPin));

      |            ^~~~~~~~~~~~~~~~~~

C:\Users\mugen\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.9.0\cores\arduino/pins_arduino.h:297:38: error: cannot convert 'volatile uint32_t*' {aka 'volatile long unsigned int*'} to 'volatile uint8_t*' {aka 'volatile unsigned char*'} in assignment

  297 | #define portOutputRegister(P)       (&(P->ODR))

      |                                     ~^~~~~~~~~~

      |                                      |

      |                                      volatile uint32_t* {aka volatile long unsigned int*}

C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.cpp:146:11: note: in expansion of macro 'portOutputRegister'

  146 |  csPort = portOutputRegister(digitalPinToPort(csPin));

      |           ^~~~~~~~~~~~~~~~~~

exit status 1

Error compiling for board Generic STM32F1 series.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sbtoonz** [comment]
Arduino: 1.8.13 (Windows 10), Board: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), STM32duino bootloader, 72Mhz (Normal), Smallest (default)"





















C:\Users\mugen\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.cpp: In member function 'void Adafruit_SPIDevice::transfer(uint8_t*, size_t)':

C:\Users\mugen\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.cpp:115:31: error: no matching function for call to 'SPIClass::transfer(uint8_t*&, size_t&)'

  115 |     _spi->transfer(buffer, len);

      |                               ^

In file included from C:\Users\mugen\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:1,

                 from C:\Users\mugen\Documents\Arduino\libraries\Adafruit_BusIO\Adafruit_SPIDevice.cpp:1:

C:\Users\mugen\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\SPI\src/SPI.h:285:11: note: candidate: 'uint8 SPIClass::transfer(uint8) const'

  285 |     uint8 transfer(uint8 data) const;

      |           ^~~~~~~~

C:\Users\mugen\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\SPI\src/SPI.h:285:11: note:   candidate expects 1 argument, 2 provided

Multiple libraries were found for "Wire.h"

 Used: C:\Users\mugen\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\Wire

 Not used: C:\Users\mugen\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\WireSlave

exit status 1

Error compiling for board Generic STM32F103C series.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by cbm80amiga** [comment]
Make sure stm32duino is properly installed. I see 
C:\Users\mugen\Documents\Arduino\libraries\Arduino_ST7735_Fast-master\Arduino_ST7735_Fast.cpp: In member function 'void Arduino_ST7735::writeSPI(uint8_t)':
Which means AVR version is used not STM32. Try to remove manually *Fast sections of defines and include and check if it compiles.
I used IDE 1.6.5, maybe 1.8 is not compatible.

**Comment by cbm80amiga** [comment]
Are you sure that proper includes are uncommented? It should look like below:
#include <Arduino_ST7735_STM.h>
...
//#include <Arduino_ST7735_Fast.h>
...

**Comment by sbtoonz** [comment]
> Are you sure that proper includes are uncommented? It should look like below:
> #include <Arduino_ST7735_STM.h>
> ...
> //#include <Arduino_ST7735_Fast.h>
> ...

yes I can attach the  example I edited as well
